# Generated by Django 3.0 on 2020-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_phone', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('employee_username', models.CharField(max_length=25)),
                ('employee_aadhar', models.ImageField(default='', upload_to='attende/aadhar')),
            ],
        ),
    ]
