# Generated by Django 3.0 on 2020-10-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
