# Generated by Django 3.0 on 2020-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0003_workdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdates',
            name='emp_latitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workdates',
            name='emp_longitude',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
