# Generated by Django 3.1.3 on 2020-11-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0006_auto_20201031_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_date', models.DateField()),
                ('emp_latitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_longitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_siteInfo', models.CharField(default='', max_length=500)),
                ('emp_work_modelNumber', models.IntegerField(blank=True, null=True)),
                ('emp_totalProdution', models.IntegerField(blank=True, null=True)),
                ('emp_running', models.IntegerField(blank=True, null=True)),
                ('emp_maintainParts', models.CharField(blank=True, default='', max_length=500)),
                ('emp_partsReason', models.CharField(blank=True, default='', max_length=500)),
                ('maintain_partsImg', models.ImageField(blank=True, default='', upload_to='attende/aadhar')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attende.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_date', models.DateField()),
                ('emp_latitudec', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_longitudec', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_latitude1', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_longitude1', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_latitude2', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_longitude2', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_latitude3', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('emp_longitude3', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('travel_from', models.CharField(blank=True, default='', max_length=100)),
                ('travel_to', models.CharField(blank=True, default='', max_length=100)),
                ('travel_by', models.CharField(blank=True, default='', max_length=100)),
                ('travel_duration', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('travel_purpose', models.CharField(blank=True, default='', max_length=100)),
                ('travel_force', models.IntegerField(blank=True, null=True)),
                ('accompanied_emp2', models.IntegerField(blank=True, null=True)),
                ('accompanied_emp3', models.IntegerField(blank=True, null=True)),
                ('accompanied_emp4', models.IntegerField(blank=True, null=True)),
                ('accompanied_emp5', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attende.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkDates',
        ),
    ]
