# Generated by Django 3.1.3 on 2020-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0007_auto_20201106_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='emp_latitude1',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emp_latitude2',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emp_latitude3',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emp_longitude1',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emp_longitude2',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emp_longitude3',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
