# Generated by Django 3.1.3 on 2020-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0008_auto_20201106_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsite',
            name='emp_totalProdution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onsite',
            name='emp_work_modelNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
