# Generated by Django 3.1.3 on 2020-11-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0009_auto_20201108_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsite',
            name='emp_running',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
