# Generated by Django 3.1.3 on 2020-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0011_employee_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_workingDates',
            field=models.CharField(default='[]', max_length=250),
        ),
    ]
