# Generated by Django 3.1.3 on 2020-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0013_travel_travel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_Image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
