# Generated by Django 3.1.3 on 2020-11-18 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0015_remove_employee_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_aadharNumber',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
