# Generated by Django 3.1.3 on 2020-11-18 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0018_auto_20201118_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('/^[0-9]+$/')]),
        ),
    ]
