# Generated by Django 3.1.3 on 2020-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0020_auto_20201118_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.IntegerField(),
        ),
    ]
