# Generated by Django 3.1.3 on 2020-11-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attende', '0022_auto_20201118_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_aadharNumber',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')]),
        ),
    ]
